INSERT INTO status_job (title) VALUES ('Developer')
INSERT INTO status_job (title) VALUES ('Devops')
INSERT INTO status_job (title) VALUES ('HR')
INSERT INTO status_job (title) VALUES ('Recruiter')
INSERT INTO status_job (title) VALUES ('TeamLead')

INSERT INTO departament (title) VALUES ('IT')
INSERT INTO departament (title) VALUES ('Java Development')
INSERT INTO departament (title) VALUES ('DevOps')
INSERT INTO departament (title) VALUES ('HR')
INSERT INTO departament (title) VALUES ('Recruiting')